### ISSUE TITLE
`get_dataset` API and unique dataset name field?

### ISSUE THREAD

**Issue by ipcamit** [colabfit/colabfit-tools#5]
Currently `get_database` needs the dataset _id field to fetch the dataset. That results in an essential call to `get_data` first as `_id` are not human memorable.

```
In [42]: client.get_data(
    ...:     "datasets",
    ...:     fields={"_id"},
    ...:     query={"name": "all_si_4"},
    ...: )
Out[42]: [array(['-235862562428816729'], dtype='<U19')]

In [45]: a = client.get_dataset("-235862562428816729")

In [46]: a["dataset"]
Out[46]: <colabfit.tools.dataset.Dataset at 0x7fb9aee61be0>
```

Will it be better if `name` field in dataset is unique and hence serves as a proxy for `_id` instead? That is, following suggested API might look better.

```
client.get_dataset("all_si_4")
```

**Comment by jvita** [comment]
You can now use the `extended-id` when calling `get_dataset()`, which is constructed as `<name>_<author_last_names_unsorted>__<short-id>`. This should be sufficient for providing human-readability.
